#!/bin/bash -x
vertMonitorStatus="$(xrandr | grep 'DP-0 connected')"
if [[ "$vertMonitorStatus" ]]; then
    xrandr --output DP-4.8 --primary --mode 2560x1440 --pos 1080x160 --rotate normal --output DP-0 --mode 1920x1080 --pos 0x0 --rotate left --output DP-1 --off --output DP-2 --off --output DP-3 --off --output HDMI-0 --off --output DP-4 --off --output DP-5 --off
else
    xrandr --output DP-4.8 --primary --mode 2560x1440 --rotate normal --output DP-0 --off --output DP-1 --off --output DP-2 --off --output DP-3 --off --output HDMI-0 --off --output DP-4 --off --output DP-5 --off
fi
[[ "$(pgrep dwm)" ]] && wallpaper.sh 
