#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

case "$1" in
"C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
"C-c")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
"C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
"C-r")      while read file; do rawtherapee "$file" & done ;;
"C-w")      while read file; do sed -i "s#--zoom $HOME/.*.[(jpg)|(png)]#--zoom $file#" $HOME/.config/xwallpaper/wallpaper.sh && wallpaper.sh; done ;;
"C-period") while read file; do convert -rotate 90 "$file" "$file"; done ;;
"C-slash")  while read file; do convert -rotate 180 "$file" "$file"; done ;;
"C-comma")  while read file; do convert -rotate 270 "$file" "$file"; done ;;
esac
