#!/bin/sh
#Show OneDrive status in dwm-bar

onedrivestatus="$(journalctl --user-unit onedrive  -n 5 | tail -n 1 | grep -o "onedrive\[[0-9]*\]: [A-Z][a-z]\+" | awk -F " " '{print $2}')"
if [[ "$onedrivestatus" = 'Downloading' ]]; then
    echo "   "
elif [[ "$onedrivestatus" = 'Uploading' ]]; then
    echo "   "
elif [[  "$onedrivestatus" = 'Creating' || "$onedrivestatus" = 'Deleting' || "$onedrivestatus" = 'Syncing' || "$onedrivestatus" = 'Moving' ]]; then
    echo "   "
elif [[  "$status" = 'Initializing' || "$status" = 'OneDrive' || "$status" = 'Sync' ]]; then
    echo "  "
else
    echo "   ✗"
fi
