#!/bin/bash
status="$(playerctl --player=spotify,mpv,%any status)"
coverUrl="$(playerctl --player=spotify,mpv,%any metadata --format "{{mpris:artUrl}}")"
coverUrl="$(echo "${coverUrl/open.spotify.com/i.scdn.co}")"
cover="/tmp/artUrl-$(echo "${coverUrl//\//}" | sed 's/https://')"
if [[ "$status" = 'Playing' || "$status" = 'Paused' ]]; then
    if [[ ! -f "$cover" ]]; then
        rm /tmp/artUrl-*
        curl "$coverUrl" -o "$cover"
    fi
    info="$(playerctl --player=spotify,mpv,%any metadata --format "{{title}}\n{{artist}}\n{{ album }}")"
    title="$(echo -e "$info" | rg -m1 "")"
    info="$(echo -e "$info" | sed 1d)"
    notify-send --hint=string:x-dunst-stack-tag:test -i "$cover" "$title" "$info"
else
    exit 1
fi
