#!/usr/bin/zsh

# -----------------------------------------------------------------------------
# Info:
#   author:    Miroslav Vidovic
#   file:      web-search.sh
#   created:   24.02.2017.-08:59:54
#   revision:  ---
#   version:   1.0
# -----------------------------------------------------------------------------
# Requirements:
#   rofi
# Description:
#   Use rofi to search the web.
# Usage:
#   web-search.sh
# -----------------------------------------------------------------------------
# Script:

BORDER="#2d2d2d"
SEPARATOR="#e6212121"
FOREGROUND="#bbbbbb"
BACKGROUND="#e6212121"
BACKGROUND_ALT="#e62d2d2d"
HIGHLIGHT_BACKGROUND="#e6444444"
HIGHLIGHT_FOREGROUND="#eeeeee"

declare -A URLS
URLS=(
  ["Google"]="https://www.google.com/search?q="
  ["Duckduckgo"]="https://www.duckduckgo.com/?q="
  ["Youtube"]="https://www.youtube.com/results?search_query="
  ["Github"]="https://github.com/search?q="
  ["StackOverflow"]="http://stackoverflow.com/search?q="
  ["Wikipedia"]="https://en.wikipedia.org/wiki/Special:Search?search="
  ["GoodReads"]="https://www.goodreads.com/search?q="
  ["SymbolHound"]="http://symbolhound.com/?q="
  ["SearchCode"]="https://searchcode.com/?q="
  ["Openhub"]="https://www.openhub.net/p?ref=homepage&query="
  ["AskUbuntu"]="http://askubuntu.com/search?q="
  ["IMDb"]="http://www.imdb.com/find?ref_=nv_sr_fn&q="
  ["RottenTomatoes"]="https://www.rottentomatoes.com/search/?search="
  ["PirateBay"]="https://thepiratebay.org/search/"
  ["Amazon"]="https://www.amazon.com/s?k="
  ["eBay"]="https://www.ebay.com/sch/i.html?_nkw=%s&LH_TitleDesc=1&_sop=12" 
  ["VimWiki"]="https://vim.fandom.com/wiki/Special:Search?search="
  ["Duckduckgo"]="https://www.duckduckgo.com/?q="
  ["WolframAlpha"]="https://www.wolframalpha.com/input/?i="
  ["Archive"]="https://web.archive.org/web/*/"
  ["Scholar"]="https://scholar.google.com/scholar?q="
  ["Google Images"]="https://www.google.com/search?tbm=isch&q=" 
)

# List for rofi
gen_list() {
    for i in "${!URLS[@]}"
    do
      echo "$i"
    done
}

main() {
  # Pass the list to rofi
  platform=$( (gen_list) | rofi -dmenu -i -matching fuzzy -no-custom -location 0 -p "Search  " \
    -hide-scrollbar true \
    -bw 1 \
    -lines 5 \
    -line-padding 10 \
    -padding 20 \
    -width 20 \
    -location 0 \
    -yoffset 22 \
    -columns 1 \
    -font "NotoSans Nerd Font 11" \
    -color-enabled true \
    -color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
    -color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND")

  if [[ -n "$platform" ]]; then
    query=$( (echo ) | rofi  -dmenu -i -matching fuzzy -location 0 -p "Query  " \
    -hide-scrollbar true \
    -bw 1 \
    -lines 0 \
    -line-padding 10 \
    -padding 20 \
    -width 20 \
    -location 0 \
    -yoffset 22 \
    -columns 1 \
    -font "NotoSans Nerd Font 11" \
    -color-enabled true)

    if [[ -n "$query" ]]; then
      # search or go to main page depending on number of arguments passed
      if [[ $# -gt 1 ]]; then
        # build search url:
        # join arguments passed with '+', then append to search engine URL
        url="${URLS[$platform]}${(j:+:)@[2,-1]}"
      else
        # build main page url:
        # split by '/', then rejoin protocol (1) and domain (2) parts with '//'
        url="${(j://:)${(s:/:)URLS[$platform]}[1,2]}"
      fi
      xdg-open "$url"
    else
      exit 1
    fi
  else
    exit 1
  fi
}

main

exit 0
