#!/bin/bash

# Custom Rofi Script
BORDER="#2d2d2d"
SEPARATOR="#e6212121"
FOREGROUND="#bbbbbb"
BACKGROUND="#e6212121"
BACKGROUND_ALT="#e62d2d2d"
HIGHLIGHT_BACKGROUND="#e6444444"
HIGHLIGHT_FOREGROUND="#eeeeee"

# Launch Rofi
#-location 0 \ # top left corner
#-font "NotoSans Nerd Font 10" \
#-width 12
MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'System' \
-hide-scrollbar true \
-bw 1 \
-lines 5 \
-line-padding 10 \
-padding 20 \
-width 20 \
-location 0 \
-yoffset 22 \
-columns 1 \
-font "NotoSans Nerd Font 16" \
-color-enabled true \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
<<< "  Lock|鈴  Sleep|  Logout|  Reboot|  Shutdown")"
case "$MENU" in
  *Lock) betterlockscreen -l;;
  *Sleep) systemctl suspend;;
  *Logout) kill -9 -1;;
  *Reboot) systemctl reboot;;
  *Shutdown) systemctl -i poweroff
esac

# More Options
# -fullscreen \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
