#!/bin/sh
[ $(pamixer --get-mute) = true ] && notify-send --hint=string:x-dunst-stack-tag:test "Volume Muted" && exit

vol="$(pamixer --get-volume)"
notify-send --hint=string:x-dunst-stack-tag:test "Volume $vol%"
