#!/bin/bash

# Custom Rofi Script
BORDER="#222D33"
SEPARATOR="#263238"
FOREGROUND="#d8d8d8"
BACKGROUND="#263238"
BACKGROUND_ALT="#263238"
HIGHLIGHT_BACKGROUND="#2F3D44"
HIGHLIGHT_FOREGROUND="#d8d8d8"

# Launch Rofi
rofi -no-lazy-grab -show drun \
-display-drun "applications" -drun-display-format "{name}" \
-hide-scrollbar true \
-bw 1 \
-lines 10 \
-line-padding 10 \
-padding 20 \
-width 30 \
-xoffset 1 -yoffset 20 \
-location 1 \
-columns 2 \
-show-icons -icon-theme "Papirus" \
-font "NotoSans 10" \
-color-enabled true \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND"

# More Options
# -fullscreen \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
